### ISSUE TITLE
Guide for idiots?

### ISSUE THREAD

**Issue by hokagay7** [typekcz/beepboop-steam#4]
Hi,
I am a newbie to these kind of stuff and was intrigued.Any chance someone could write an idiots guide on how to install? Where do dependencies need to be installed to? Etc?
Thanks!

**Comment by typekcz** [comment]
Hello,
this project uses npm that manages dependencies for you.
Only thing you have to install is [Node.js](https://nodejs.org/en/) that also contains npm.
Then you can follow guide in [README.md](https://github.com/typekcz/beepboop-steam/blob/master/README.md).
You have to provide configuration (easiest by creating file config.js in projects folder) and then you can run commans shown in installation section.
On Windows you can run these commands in PowerShell. You can open PowerShell by holding shift and right clicking the "beepboop-steam-master" folder and then choosing "Open PowerShell here".

I understand that this can look complicated for someone who is not familiar with this stuff.
If you want you can add me on Steam and I will guide you through it.

**Comment by hokagay7** [comment]
> Hello,
> this project uses npm that manages dependencies for you.
> Only thing you have to install is [Node.js](https://nodejs.org/en/) that also contains npm.
> Then you can follow guide in [README.md](https://github.com/typekcz/beepboop-steam/blob/master/README.md).
> You have to provide configuration (easiest by creating file config.js in projects folder) and then you can run commans shown in installation section.
> On Windows you can run these commands in PowerShell. You can open PowerShell by holding shift and right clicking the "beepboop-steam-master" folder and then choosing "Open PowerShell here".
> 
> I understand that this can look complicated for someone who is not familiar with this stuff.
> If you want you can add me on Steam and I will guide you through it.

i manage to make it run..but when i try to play sound i got this error
![error](https://user-images.githubusercontent.com/68209911/105316278-9d5d7a00-5bfb-11eb-9eaf-37737fbca832.PNG)

did i do anything wrong?

**Comment by typekcz** [comment]
Yes, that is expected. That's because by default BeepBoop uses open source version of Chrome called Chromium that does not include non-free codecs.

To run BeebBoop on regular Chrome you have to run this command before launching:
`$env:PUPPETEER_EXECUTABLE_PATH="C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"`
This is for PowerShell and you need to have Chrome installed in that path.
In cmd it should be:
`set PUPPETEER_EXECUTABLE_PATH=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`

I also forgot to mention that if you want to store your own sounds in BeepBoop, you have to set up a PostgreSQL database.
But this is optional and BeepBoop should run fine without it, but with some features not working.

I should probably rewrite installation guide to include this stuff.

**Comment by hokagay7** [comment]
> Yes, that is expected. That's because by default BeepBoop uses open source version of Chrome called Chromium that does not include non-free codecs.
> 
> To run BeebBoop on regular Chrome you have to run this command before launching:
> `$env:PUPPETEER_EXECUTABLE_PATH="C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"`
> This is for PowerShell and you need to have Chrome installed in that path.
> In cmd it should be:
> `set PUPPETEER_EXECUTABLE_PATH=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`
> 
> I also forgot to mention that if you want to store your own sounds in BeepBoop, you have to set up a PostgreSQL database.
> But this is optional and BeepBoop should run fine without it, but with some features not working.
> 
> I should probably rewrite installation guide to include this stuff.

Dude it works now..but the only problem is, it took long time for the bot to play audio.Nice job actually

**Comment by hokagay7** [comment]
i read the command prompt and it show this
![error cmd](https://user-images.githubusercontent.com/68209911/105372436-9016ae80-5c40-11eb-91c6-89cdd9a05388.PNG)

it took about 12 min to play an audio by search.Roughly 6 min to play url.Thoughts?

**Comment by typekcz** [comment]
That is weird. It should play almost instantly. I tried those URLs on my machine and on my Heroku instance and both played it almost instantly.
I have no idea what could be going on...
I use ytdl-core to pipe data stream to the player so it doesn't download whole youtube video but is streaming it. Even 10 hours long videos start playing immediately.

**Comment by hokagay7** [comment]
> That is weird. It should play almost instantly. I tried those URLs on my machine and on my Heroku instance and both played it almost instantly.
> I have no idea what could be going on...
> I use ytdl-core to pipe data stream to the player so it doesn't download whole youtube video but is streaming it. Even 10 hours long videos start playing immediately.

Dude you are a genius.I reinstall the dependencies,then start it using powershell instead of node.I use node in the first place because of powershell restriction.I managed to make it run and now everything work just fine.TQ for guiding me :)

**Comment by hokagay7** [comment]
for the second time,,i shouldn't closed issue, other people might need help :p

**Comment by typekcz** [comment]
I'm glad you made it work. I still don't understand why that was happening.
Anyway I'm going to convert this to discussion because it's not really an issue.
I also want to rewrite installation guide to be more thorough.
