### ISSUE TITLE
puppeteer executable path for glitch/heroku

### ISSUE THREAD

**Issue by hokagay7** [typekcz/beepboop-steam#6]
hey its me again 😅.Lately ive been trying to run beepboop on glitch.It run just fine,but the problem is the puppeteer.You said that beep use "non-free codecs" so i need to use regular chrome instead of chromium.How do i do it on glitch or heroku? I can install the dependencies,but how bout the chrome?

TQ

**Comment by typekcz** [comment]
I actually [covered installation on Heroku in my README](https://github.com/typekcz/beepboop-steam#Instalation) and published [this fork of puppeteer buildpack](https://github.com/typekcz/puppeteer-heroku-buildpack) specifically for BeepBoop.

I don't know about Glitch but if you can install packages there somehow, you can look at [this file](https://github.com/typekcz/puppeteer-heroku-buildpack/blob/master/bin/compile) which packages to install. It's actualy Chromium but with extra stuff.

**Comment by hokagay7** [comment]
I cant seems to make it work on heroku.The bot instant shutdown after there is an output.
I already install the buildpack and stuff but i still encounter the "element has no supported sources" error.I might be missing something.

**Comment by typekcz** [comment]
You have to set these environment variables in Heroku:
```
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=
PUPPETEER_EXECUTABLE_PATH="/usr/lib/chromium-browser/chromium-browser"
```
