### ISSUE TITLE
Attempting to make a play pause

### ISSUE THREAD

**Issue by hokagay7** [typekcz/beepboop-steam#8]
This is my attempt to make the bot play and pause audio:

    playPause(){
		return this.page.evaluate(() => {
			window.audio.play();
			return true;
		});
	}

	stopSound(){
		return this.page.evaluate(() => {
			window.audio.pause();
			return true;
		});
	}

I tried to cause apparently you coded the bot to pause audio, why not making a play/pause command too? I'm still learning JavaScript at school so I don't know much about JavaScript. So what I did is copy your code back and change it :P
It indeed play and pause the audio BUT the audio is overlapping. I meant the bot is playing two audio (I set _headless: false_ to verify this).

**Comment by typekcz** [comment]
So you did it correctly, but when you set headless to false, then you hear sound from bot's browser and you probably were in a voice room with bot, so you heard it from both bot's browser and your Steam chat.

I added the feature, you can check it out here: 0588ecc15e1041bacd053c8a94fd6aaf19ab876a
You can use "pause" or "stop" command to pause and then "play" to resume.
